export const OWN_WORK_PACKAGE_NAME = "own-work";
export * from "./coordination.js";
export * from "./lifecycle.js";
export * from "./roadmap.js";
export * from "./schemas.js";
export * from "./semantics.js";
export * from "./spec.js";
export * from "./systems-registry.js";
export * from "./task.js";
export { createProgram, runCli } from "./program.js";
export type { CliOutput, CreateProgramOptions } from "./program.js";
